// Dictionnaire de l'APK : la clé est le texte français affiché dans le code (avec {repères} remplis à l'affichage).
// `ar` : arabe classique ; `hyb` : mode hybride, absent = comme `ar`. Règle d'Issam (2026-10-07) : en hybride, une
// phrase arabe ne garde un mot français que s'il s'agit de « Réfection » (et « Polyethylene », version d'Issam) ;
// les libellés entièrement en français (Balayage, Secteur, listes de choix…) restent, sauf ceux des fuites (en arabe). Tout relu et validé par Issam dans l'artefact
// « Dictionnaire arabe APK » (docs/traduction/).

export interface Entree { ar: string; hyb?: string }

export const TRADUCTIONS = {
  // Général
  'Suivi des fuites': { ar: 'تتبع التسربات' },
  'Application non configurée (adresse du serveur absente).': { ar: 'التطبيق غير مُهيّأ (عنوان الخادم غير موجود).' },
  "Aucun marché n'est affecté à votre compte. Contactez l'administrateur.": { ar: 'لا توجد أي صفقة مرتبطة بحسابك. اتصل بمسؤول النظام.' },
  'Retour': { ar: 'رجوع' },
  'Chargement…': { ar: 'جارٍ التحميل…' },
  'Quitter': { ar: 'خروج' },
  'Annuler': { ar: 'إلغاء' },
  'Non': { ar: 'لا' },

  // Connexion
  'Connexion': { ar: 'تسجيل الدخول' },
  'Identifiant': { ar: 'اسم المستخدم' },
  'Mot de passe': { ar: 'كلمة المرور' },
  'Se connecter': { ar: 'دخول' },
  'Identifiant ou mot de passe incorrect.': { ar: 'اسم المستخدم أو كلمة المرور غير صحيحة.' },
  'Connexion impossible : vérifiez le réseau.': { ar: 'تعذّر الدخول: تحقّق من الاتصال بالإنترنت.' },
  'Bonjour': { ar: 'مرحبًا' },
  'Connectez-vous pour continuer': { ar: 'سجّل الدخول للمتابعة' },
  "Entrez l'identifiant et le mot de passe remis par l'administrateur.": { ar: 'أدخل اسم المستخدم وكلمة المرور اللذين سلّمهما لك مسؤول النظام.' },
  'ex. agent1': { ar: 'مثال: agent1' },
  "La session reste ouverte sur cette tablette jusqu'à « Quitter ».": { ar: 'تبقى الجلسة مفتوحة على هذا الجهاز اللوحي إلى أن تضغط «خروج».' },
  'Connexion…': { ar: 'جارٍ الدخول…' },

  // Liste des fuites
  'Fuites · {code}': { ar: 'التسربات · {code}' },
  'Balayage': { ar: 'مسح الشبكة', hyb: 'Balayage' },
  'Hors ligne : dernière liste connue.': { ar: 'دون اتصال: آخر قائمة محفوظة.' },
  'Aucune fuite.': { ar: 'لا يوجد أي تسرب.' },
  'Gardée sur la tablette': { ar: 'محفوظة على الجهاز اللوحي' },
  '{date} · gardée sur la tablette': { ar: '{date} · محفوظة على الجهاز اللوحي' },
  'N° {numero}': { ar: 'رقم {numero}' },
  'Fuite N° {numero}': { ar: 'التسرب رقم {numero}' },
  'Non réparée > {delai} h': { ar: 'لم يُصلَح > {delai} ساعة' },
  'Y aller': { ar: 'الذهاب إلى الموقع' },
  'Y aller (pas de position GPS)': { ar: 'الذهاب إلى الموقع (لا يوجد موقع GPS)' },
  'Référence client': { ar: 'مرجع الزبون' },
  'Fuites': { ar: 'التسربات' },
  'Toutes': { ar: 'الكل' },
  '{n} fuites': { ar: 'عدد التسربات: {n}' },
  '{n} affichées sur {total}': { ar: 'المعروضة: {n} من {total}' },
  'À envoyer': { ar: 'للإرسال' },
  'N°, référence ou adresse': { ar: 'الرقم أو المرجع أو العنوان' },
  'Rechercher une fuite': { ar: 'البحث عن تسرب' },
  'Effacer la recherche': { ar: 'مسح البحث' },
  'N°': { ar: 'رقم' },
  'Secteur · adresse': { ar: 'القطاع · العنوان' },
  'Détectée le': { ar: 'تاريخ الكشف' },
  'Statut': { ar: 'الحالة' },
  'Alertes': { ar: 'التنبيهات' },
  'Photos': { ar: 'الصور' },
  'Chargement des fuites…': { ar: 'جارٍ تحميل التسربات…' },
  'Aucune fuite ne correspond.': { ar: 'لا يوجد أي تسرب مطابق.' },
  'Secteur non renseigné': { ar: 'القطاع غير محدد' },

  // Statuts
  'Détectée, non réparée': { ar: 'تم الكشف، لم يتم الإصلاح' },
  'Réparation en cours': { ar: 'الإصلاح جارٍ' },
  'Réparée': { ar: 'تم الإصلاح' },
  'Achevée': { ar: 'مكتمل' },
  'Sans réparation': { ar: 'بدون إصلاح' },
  'Réparée, réfection à faire': { ar: 'تم الإصلاح، إعادة الرصف متبقية', hyb: 'تم الإصلاح، الـ Réfection متبقية' },
  'Détectée': { ar: 'تم الكشف', hyb: 'Détectée' },
  'En cours': { ar: 'جارٍ' },

  // Nouvelle fuite
  'Nouvelle fuite': { ar: 'تسرب جديد' },
  'Position': { ar: 'الموقع' },
  'Recherche de la position…': { ar: 'جارٍ تحديد الموقع…' },
  'Actualiser la position': { ar: 'تحديث الموقع' },
  'Position refusée : autorisez la localisation dans les réglages de la tablette.': { ar: 'تم رفض تحديد الموقع: فعّل خاصية الموقع في إعدادات الجهاز اللوحي.' },
  "Position introuvable. Sortez à l'air libre et réessayez.": { ar: 'تعذّر تحديد الموقع. اخرج إلى مكان مكشوف وأعد المحاولة.' },
  "Sans réseau : pas de contrôle des doublons. Vérifiez sur place qu'elle n'est pas déjà signalée.": {
    ar: 'لا يوجد اتصال: لا يمكن التحقق من التكرار. تأكّد في عين المكان أن هذا التسرب لم يُبلَّغ عنه من قبل.',
   
  },
  'Fuite déjà signalée ici ?': { ar: 'هل سبق الإبلاغ عن تسرب هنا؟' },
  ' · même référence': { ar: ' · نفس المرجع' },
  ' · à {n} m': { ar: ' · على بُعد {n} م' },
  "C'est la même fuite": { ar: 'إنه نفس التسرب' },
  'Nouvelle fuite liée': { ar: 'تسرب جديد مرتبط' },
  'Elle sera enregistrée comme nouvelle fuite liée au N° {numero}.': { ar: 'سيُسجَّل كتسرب جديد مرتبط بالرقم {numero}.' },
  'Sans choix, elle sera enregistrée comme une nouvelle fuite indépendante.': { ar: 'بدون اختيار، سيُسجَّل كتسرب جديد مستقل.' },
  'Même fuite': { ar: 'نفس التسرب' },
  'La saisie en cours et ses photos ne seront pas gardées. Ouvrir la fiche existante ?': { ar: 'لن يُحتفَظ بالإدخال الحالي وصوره. هل تريد فتح البطاقة الموجودة؟' },
  'Oui, ouvrir la fiche': { ar: 'نعم، افتح البطاقة' },
  'Secteur': { ar: 'القطاع', hyb: 'Secteur' },
  'Choisir le secteur': { ar: 'اختر القطاع' },
  'Aucun': { ar: 'لا شيء' },
  'Adresse / repère': { ar: 'العنوان / معلم قريب' },
  'Observation': { ar: 'ملاحظة' },
  'Prendre une photo': { ar: 'التقاط صورة' },
  'Enregistrer la fuite': { ar: 'تسجيل التسرب' },
  "Indiquez au moins la position GPS, la {reference} ou l'adresse.": { ar: 'أدخل على الأقل موقع GPS أو {reference} أو العنوان.' },
  'Enregistrement sur la tablette…': { ar: 'جارٍ الحفظ على الجهاز اللوحي…' },
  'Envoi…': { ar: 'جارٍ الإرسال…' },
  'Photo impossible : {erreur}': { ar: 'تعذّر التقاط الصورة: {erreur}' },
  'Appareil photo refusé : autorisez-le dans les réglages de la tablette.': { ar: 'تم رفض الوصول إلى الكاميرا: اسمح به في إعدادات الجهاز اللوحي.' },
  'Identification': { ar: 'بيانات التعريف' },
  'Facultatives ; un appui sur une photo la retire.': { ar: 'اختيارية؛ اضغط على صورة لإزالتها.' },
  '{n} secteurs': { ar: 'عدد القطاعات: {n}' },

  // Types de photo
  'Détection': { ar: 'الكشف', hyb: 'Détection' },
  'Avant': { ar: 'قبل' },
  'Pendant': { ar: 'أثناء' },
  'Après': { ar: 'بعد' },
  'Réfection': { ar: 'إعادة الرصف', hyb: 'Réfection' },
  'Autre': { ar: 'أخرى' },

  // Envois en attente
  'Envois en attente': { ar: 'الإرسالات المعلّقة' },
  "Ces saisies sont gardées sur la tablette. Elles partent dans l'ordre dès que le réseau revient ; ne désinstallez pas l'application avant.": {
    ar: 'هذه الإدخالات محفوظة على الجهاز اللوحي، وتُرسَل بالترتيب فور عودة الاتصال. لا تحذف التطبيق قبل ذلك.',
  },
  'Envoyer maintenant': { ar: 'أرسِل الآن' },
  'Tout est envoyé.': { ar: 'تم إرسال كل شيء.' },
  'Envoi impossible pour le moment.': { ar: 'تعذّر الإرسال حاليًا.' },
  '{n} envoi(s) restent à traiter.': { ar: 'إرسالات متبقية: {n}' },
  'Saisie le {date} · {n} photo(s) en attente': { ar: 'أُدخِل في {date} · صور في الانتظار: {n}' },
  'Supprimer de la tablette': { ar: 'حذف من الجهاز اللوحي' },
  'Supprimer de la tablette ?': { ar: 'حذف من الجهاز اللوحي؟' },
  'Cette saisie et ses photos seront définitivement perdues.': { ar: 'سيُفقَد هذا الإدخال وصوره نهائيًا.' },
  'Cette saisie et {n} saisie(s) liée(s) (réparation, réfection, modification, photos) et ses photos seront définitivement perdues.': {
    ar: 'سيُفقَد هذا الإدخال ومعه {n} إدخالات مرتبطة (إصلاح، إعادة رصف، تعديل، صور) وصوره نهائيًا.',
    hyb: 'سيُفقَد هذا الإدخال ومعه {n} إدخالات مرتبطة (Réparation، Réfection، تعديل، صور) وصوره نهائيًا.',
  },
  'Garder': { ar: 'احتفِظ' },
  'Supprimer': { ar: 'احذف' },
  'Réparation · {fuite}': { ar: 'إصلاح · {fuite}' },
  'Réfection · {fuite}': { ar: 'إعادة الرصف · {fuite}', hyb: 'Réfection · {fuite}' },
  'Modification de réparation · {fuite}': { ar: 'تعديل الإصلاح · {fuite}' },
  'Photo(s) ajoutée(s) · {fuite}': { ar: 'صور مضافة · {fuite}' },
  'Nouvelle fuite · {reference}': { ar: 'تسرب جديد · {reference}' },
  'sans référence': { ar: 'بدون مرجع' },
  '{n} saisies sur la tablette': { ar: 'إدخالات على الجهاز اللوحي: {n}' },
  'Aucune saisie en attente.': { ar: 'لا توجد إدخالات في الانتظار.' },
  'Refusée par le serveur : {erreur}': { ar: 'رفضها الخادم: {erreur}' },

  // Fiche de la fuite
  'Fiche de la fuite': { ar: 'بطاقة التسرب' },
  'Fuite à envoyer': { ar: 'تسرب للإرسال' },
  'Fuite à envoyer ({reference})': { ar: 'تسرب للإرسال ({reference})' },
  'Fiche jamais ouverte sur cette tablette : elle sera disponible au retour du réseau.': { ar: 'لم تُفتح هذه البطاقة من قبل على هذا الجهاز اللوحي: ستكون متاحة عند عودة الاتصال.' },
  'Fuite introuvable ou accès refusé.': { ar: 'التسرب غير موجود أو الوصول مرفوض.' },
  'Liste des fuites': { ar: 'قائمة التسربات' },
  'Hors ligne : dernière version connue de la fiche.': { ar: 'دون اتصال: آخر نسخة محفوظة من البطاقة.' },
  'Cette fuite est encore sur la tablette : elle partira au retour du réseau.': { ar: 'هذا التسرب ما زال على الجهاز اللوحي: سيُرسَل عند عودة الاتصال.' },
  "Fuite verrouillée le {date} (lot d'attachement arrêté)": { ar: 'تسرب مُقفَل بتاريخ {date} (دفعة كشف الأشغال مُغلَقة)' },
  ' : saisie et modification réservées au responsable.': { ar: ': الإدخال والتعديل مخصّصان للمسؤول.' },
  'Ouvrage': { ar: 'المنشأة', hyb: 'Ouvrage' },
  '{date} par {agent}': { ar: '{date} بواسطة {agent}' },
  'Re-détection': { ar: 'إعادة الكشف', hyb: 'Re-détection' },
  'liée à une fuite déjà signalée': { ar: 'مرتبط بتسرب مُبلَّغ عنه سابقًا' },
  'Motif': { ar: 'السبب' },
  'Aucune photo.': { ar: 'لا توجد صور.' },
  'Ajouter une photo de la fuite': { ar: 'إضافة صورة للتسرب' },
  'Photo': { ar: 'صورة' },
  '{type} (à envoyer)': { ar: '{type} (للإرسال)' },
  'Visible avec le réseau': { ar: 'تظهر عند توفّر الاتصال' },
  'Retirer': { ar: 'إزالة' },
  'Réparations': { ar: 'الإصلاحات' },
  'Aucune réparation saisie.': { ar: 'لم يُدخَل أي إصلاح.' },
  'Saisir une réparation': { ar: 'إدخال إصلاح' },
  'Réfections': { ar: 'أشغال إعادة الرصف', hyb: 'Réfections' },
  'Aucune réfection saisie.': { ar: 'لم تُدخَل أي إعادة رصف.', hyb: 'لم تُدخَل أي Réfection.' },
  'Saisir une réfection': { ar: 'إدخال إعادة رصف', hyb: 'إدخال Réfection' },
  'Sur la tablette, envoi au retour du réseau.': { ar: 'على الجهاز اللوحي، يُرسَل عند عودة الاتصال.' },
  'Modification sur la tablette, envoi au retour du réseau.': { ar: 'تعديل على الجهاز اللوحي، يُرسَل عند عودة الاتصال.' },
  'tuyau réparé': { ar: 'أنبوب مُصلَح' },
  'robinet PEC changé': { ar: 'محبس التفريع مُستبدَل' },
  'collier PEC changé': { ar: 'طوق التفريع مُستبدَل' },
  'bouche à clé mise à niveau': { ar: 'غطاء المحبس مُسوّى مع السطح' },
  'élément remplacé': { ar: 'عنصر مُستبدَل' },
  '{l} × {la} × {p} m': { ar: '{l} × {la} × {p} م' },
  'Ø {d} mm': { ar: 'Ø {d} مم' },
  ' · PE {n} m': { ar: ' · بولي إيثيلين {n} م' },
  'Ajouter une photo :': { ar: 'إضافة صورة:' },
  'Modifier la réparation': { ar: 'تعديل الإصلاح' },
  'Réfection faite': { ar: 'تمت إعادة الرصف', hyb: 'Réfection مُنجَزة' },
  'Clôturée sans réfection': { ar: 'أُغلِق بدون إعادة رصف', hyb: 'مُغلَقة بدون Réfection' },
  'Revêtement prévu à la réparation': { ar: 'طبقة الرصف المُقرَّرة عند الإصلاح' },
  'dimensions de la fouille': { ar: 'أبعاد الحفرة' },
  'Ajouter une photo de réfection': { ar: 'إضافة صورة إعادة الرصف', hyb: 'إضافة صورة Réfection' },
  'Nature': { ar: 'نوع طبقة الرصف' },
  'Réf. {ref}': { ar: 'المرجع {ref}', hyb: 'Réf. {ref}' },
  'Sans référence ni adresse': { ar: 'بدون مرجع ولا عنوان' },
  'Interventions saisies sur le terrain ou au bureau.': { ar: 'التدخلات المُدخلة في الميدان أو في المكتب.' },
  'Remise en état du revêtement après la réparation.': {
    ar: 'إعادة طبقة الرصف إلى حالتها بعد الإصلاح.',
  },
  'Pas encore envoyée : {erreur}': { ar: 'لم تُرسَل بعد: {erreur}' },
  'Modification pas encore envoyée : {erreur}': { ar: 'التعديل لم يُرسَل بعد: {erreur}' },
  'Travaux': { ar: 'الأشغال' },
  'Représentant présent': { ar: 'الممثل الحاضر' },
  'Pièces': { ar: 'القطع' },
  'Ouvriers': { ar: 'العمال' },
  'Dimensions': { ar: 'الأبعاد' },
  '{l} × {la} m': { ar: '{l} × {la} م' },
  'Pièce': { ar: 'قطعة' },

  // Saisie d'une réparation
  'Nouvelle réparation': { ar: 'إصلاح جديد' },
  "Corrigez ce qui doit l'être, puis « Enregistrer les modifications ». Les photos prises ici s'ajoutent à celles déjà envoyées.": {
    ar: 'صحّح ما يلزم، ثم اضغط «حفظ التعديلات». الصور الملتقطة هنا تُضاف إلى الصور المُرسَلة سابقًا.',
  },
  'Résultat': { ar: 'النتيجة' },
  'En cours / reste à finir': { ar: 'جارٍ / لم يكتمل بعد' },
  'Non réparée': { ar: 'لم يتم الإصلاح' },
  'Motif (obligatoire)': { ar: 'السبب (إجباري)' },
  'Date et heure des travaux': { ar: 'تاريخ وساعة الأشغال' },
  'JJ/MM/AAAA': { ar: 'يوم/شهر/سنة', hyb: 'JJ/MM/AAAA' },
  'HH:MM': { ar: 'ساعة:دقيقة', hyb: 'HH:MM' },
  'Maintenant': { ar: 'الآن' },
  'Date ou heure invalide (JJ/MM/AAAA et HH:MM).': { ar: 'تاريخ أو ساعة غير صالحة (يوم/شهر/سنة و ساعة:دقيقة).' },
  'La date est dans le futur : vérifiez-la.': { ar: 'التاريخ في المستقبل: تحقّق منه.' },
  'Équipe': { ar: 'الفريق' },
  'Constat': { ar: 'المعاينة' },
  'Matériau': { ar: 'المادة' },
  'Diamètre (mm) : DE pour le PE, DN pour les conduites': {
    ar: 'القطر (مم): القطر الخارجي لأنابيب البولي إيثيلين، والقطر الاسمي للقنوات',
  },
  'Travaux réalisés': { ar: 'الأشغال المنجزة' },
  'Tuyau / conduite réparé(e)': { ar: 'أنبوب / قناة مُصلَحة' },
  'Robinet PEC changé': { ar: 'محبس التفريع مُستبدَل' },
  'Collier PEC changé': { ar: 'طوق التفريع مُستبدَل' },
  'Bouche à clé mise à niveau': { ar: 'غطاء المحبس مُسوّى مع السطح' },
  'Élément de conduite remplacé': { ar: 'عنصر من القناة مُستبدَل' },
  'Longueur de PE posée (m)': { ar: 'طول أنبوب البولي إيثيلين المُركَّب (م)', hyb: 'طول الـ Polyethylene المُركَّب (م)' },
  'Fouille': { ar: 'الحفرة', hyb: 'Fouille' },
  'Longueur (m)': { ar: 'الطول (م)' },
  'Largeur (m)': { ar: 'العرض (م)' },
  'Profondeur (m)': { ar: 'العمق (م)' },
  'Longueur supérieure à 2 m : à justifier par un élément de conduite remplacé.': {
    ar: 'طول يتجاوز 2 م: يجب تبريره باستبدال عنصر من القناة.',
  },
  'Revêtement à refaire': { ar: 'طبقة الرصف المطلوب إعادتها' },
  'Emplacement': { ar: 'المكان' },
  'Représentant {sigle} présent (nom)': { ar: 'ممثل {sigle} الحاضر (الاسم)' },
  "du maître d'ouvrage": { ar: 'صاحب المشروع' },
  'Pièces posées': { ar: 'القطع المُركَّبة' },
  'Quantité : {designation}': { ar: 'الكمية: {designation}' },
  '(libre)': { ar: '(حرّة)' },
  'Retrait : responsable': { ar: 'الإزالة: المسؤول فقط' },
  'Rechercher un article': { ar: 'البحث عن صنف' },
  'ex. collier 63': { ar: 'مثال: collier 63' },
  'Quantité': { ar: 'الكمية' },
  'Liste des articles pas encore chargée sur cette tablette : connectez-la au réseau.': { ar: 'قائمة الأصناف لم تُحمَّل بعد على هذا الجهاز اللوحي: اربطه بالإنترنت.' },
  'Ouvriers (facultatif)': { ar: 'العمال (اختياري)' },
  'Enregistrer la réparation': { ar: 'حفظ الإصلاح' },
  'Enregistrer les modifications': { ar: 'حفظ التعديلات' },
  'Choisissez le résultat.': { ar: 'اختر النتيجة.' },
  'Fuite non réparée : choisissez le motif.': { ar: 'تسرب لم يُصلَح: اختر السبب.' },
  'Valeur numérique invalide : « {valeur} ».': { ar: 'قيمة رقمية غير صالحة: «{valeur}».' },
  'Diamètre : un nombre entier de millimètres.': { ar: 'القطر: عدد صحيح بالمليمتر.' },
  'Quantité de « {designation} » : un nombre supérieur à 0.': { ar: 'كمية «{designation}»: عدد أكبر من 0.' },
  'Quantité de la pièce : un nombre supérieur à 0.': { ar: 'كمية القطعة: عدد أكبر من 0.' },
  'Aucune modification à enregistrer.': { ar: 'لا توجد تعديلات للحفظ.' },
  'Enregistrement sur la tablette impossible : {erreur}': { ar: 'تعذّر الحفظ على الجهاز اللوحي: {erreur}' },
  "Aucun article ne correspond. S'il manque, notez-le en observation : le responsable demandera sa création dans Dolibarr.": {
    ar: 'لا يوجد صنف مطابق. إذا كان ناقصًا، دوّنه في الملاحظة: سيطلب المسؤول إضافته في Dolibarr.',
  },

  // Saisie d'une réfection
  'Nouvelle réfection': { ar: 'إعادة رصف جديدة', hyb: 'Réfection جديدة' },
  'Non faite (motif)': { ar: 'غير مُنجَزة (السبب)' },
  'Nature (vide : {nature}, prévue à la réparation)': {
    ar: 'نوع طبقة الرصف (فارغ: {nature}، المُقرَّرة عند الإصلاح)',
  },
  'Laissées vides, longueur et largeur sont reprises de la fouille.': {
    ar: 'إذا تُرك الطول والعرض فارغَين، تُعتمَد أبعاد الحفرة.',
  },
  '{valeur} (fouille)': { ar: '{valeur} (الحفرة)', hyb: '{valeur} (Fouille)' },
  'Indiquez si la réfection est faite.': { ar: 'حدّد هل تمت إعادة الرصف.', hyb: 'حدّد هل الـ Réfection مُنجَزة.' },
  "Choisissez la nature de la réfection (aucune n'est prévue à la réparation).": {
    ar: 'اختر نوع إعادة الرصف (لم يُحدَّد أي نوع عند الإصلاح).', hyb: 'اختر نوع الـ Réfection (لم يُحدَّد أي نوع عند الـ Réparation).',
  },
  'Réfection non faite : choisissez le motif.': { ar: 'إعادة الرصف غير مُنجَزة: اختر السبب.', hyb: 'Réfection غير مُنجَزة: اختر السبب.' },
  'Longueur ou largeur invalide.': { ar: 'طول أو عرض غير صالح.' },
  'Enregistrer la réfection': { ar: 'حفظ إعادة الرصف', hyb: 'حفظ الـ Réfection' },

  // Listes de choix
  'Branchement': { ar: 'ربط', hyb: 'Branchement' },
  'Conduite': { ar: 'قناة', hyb: 'Conduite' },
  'Pièce spéciale': { ar: 'قطعة خاصة', hyb: 'Pièce spéciale' },
  "Bouche d'incendie": { ar: 'فوهة إطفاء الحريق', hyb: "Bouche d'incendie" },
  'Vanne': { ar: 'صمام', hyb: 'Vanne' },
  'Compteur': { ar: 'عداد', hyb: 'Compteur' },
  'Branchement clandestin': { ar: 'ربط غير قانوني', hyb: 'Branchement clandestin' },
  'PE': { ar: 'بولي إيثيلين (PE)', hyb: 'PE' },
  'Amiante-ciment': { ar: 'أسمنت أميانتي', hyb: 'Amiante-ciment' },
  'PVC': { ar: 'بي في سي (PVC)', hyb: 'PVC' },
  'Fonte ductile': { ar: 'حديد زهر مرن', hyb: 'Fonte ductile' },
  'Fonte grise': { ar: 'حديد زهر رمادي', hyb: 'Fonte grise' },
  'Acier galvanisé': { ar: 'فولاذ مجلفن', hyb: 'Acier galvanisé' },
  'PPR': { ar: 'بولي بروبيلين (PPR)', hyb: 'PPR' },
  'Trottoir': { ar: 'رصيف', hyb: 'Trottoir' },
  'Chaussée': { ar: 'طريق معبّد', hyb: 'Chaussée' },
  'Terrain naturel': { ar: 'أرض طبيعية' },

  // Balayage
  'Carte du réseau': { ar: 'خريطة الشبكة' },
  'La carte du réseau a besoin de la connexion.': { ar: 'خريطة الشبكة تحتاج إلى الاتصال بالإنترنت.' },
  'Chargement de la carte…': { ar: 'جارٍ تحميل الخريطة…' },
  'Session expirée : reconnectez-vous.': { ar: 'انتهت الجلسة: سجّل الدخول من جديد.' },
  'Réessayer': { ar: 'إعادة المحاولة' },
  'Retour à la liste': { ar: 'العودة إلى القائمة' },
  'Le panneau web ne répond pas (erreur {code}). Réessayez dans un instant.': { ar: 'الموقع لا يستجيب (خطأ {code}). أعد المحاولة بعد لحظة.' },
  "La carte s'est arrêtée. Réessayez.": { ar: 'توقّفت الخريطة. أعد المحاولة.' },

  // Messages d'envoi
  "Fuite verrouillée (lot d'attachement arrêté) : seul le responsable peut encore la compléter ou la modifier. Rien n'est perdu : prévenez le responsable, puis « Envoyer maintenant ».": {
    ar: 'تسرب مُقفَل (دفعة كشف الأشغال مُغلَقة): المسؤول وحده يمكنه إتمامه أو تعديله. لم يضِع شيء: أخبِر المسؤول، ثم اضغط «أرسِل الآن».',
  },
  "Droit insuffisant sur ce marché pour cette saisie. Rien n'est perdu : voyez avec l'administrateur.": {
    ar: 'صلاحيات غير كافية على هذه الصفقة لهذا الإدخال. لم يضِع شيء: راجِع مسؤول النظام.',
  },
  'Fuite ou paramètre introuvable sur le serveur (supprimé entre-temps ?).': { ar: 'التسرب أو الإعداد غير موجود على الخادم (ربما حُذف؟).' },
  'Pièce sans article de la liste (ancienne désignation libre) refusée : retirez-la et choisissez un article proposé.': {
    ar: 'قطعة غير موجودة في قائمة الأصناف (تسمية حرّة قديمة) مرفوضة: أزِلها واختر صنفًا من القائمة.',
  },
  'Saisie incomplète refusée par le serveur ({detail}).': { ar: 'إدخال ناقص رفضه الخادم ({detail}).' },
  'Modification non autorisée': { ar: 'تعديل غير مسموح به' },
  "En attente : une saisie précédente de cette fuite n'est pas encore passée.": { ar: 'في الانتظار: إدخال سابق لهذا التسرب لم يُرسَل بعد.' },

  'Visible': { ar: 'ظاهرة', hyb: 'Visible' },
  'Invisible': { ar: 'غير ظاهرة', hyb: 'Invisible' },
  // Chantier v2 (S7, 2026-10-09) : validation, saisie, gardes-fous, notifications, mise à jour — à relire par Issam
  'Réparation': { ar: 'الإصلاح', hyb: 'Réparation' },
  'À valider': { ar: 'للمصادقة' },
  'Valider': { ar: 'صادِق' },
  'Validation': { ar: 'المصادقة' },
  'Validée le {date}': { ar: 'صودِق عليها في {date}' },
  'Valider ({n})': { ar: 'صادِق ({n})' },
  '{n} étape(s) validée(s).': { ar: 'تمت المصادقة على {n} مرحلة.' },
  'Aucune photo': { ar: 'لا توجد صورة' },
  '{n} étape(s) sans photo. Valider quand même ?': { ar: '{n} مرحلة بدون صورة. هل تريد المصادقة رغم ذلك؟' },
  "Cette étape n'a aucune photo. Valider quand même ?": { ar: 'هذه المرحلة ليست لها أي صورة. هل تريد المصادقة رغم ذلك؟' },
  'Valider sans photo': { ar: 'صادِق بدون صورة' },
  'La validation a besoin de la connexion.': { ar: 'المصادقة تحتاج إلى الاتصال بالإنترنت.' },
  'Tout cocher': { ar: 'تحديد الكل' },
  'Tout décocher': { ar: 'إلغاء تحديد الكل' },
  'Rien à valider.': { ar: 'لا شيء للمصادقة.' },
  'Aucune photo : ouvrir la fiche pour en ajouter': { ar: 'لا توجد صورة: افتح البطاقة لإضافة صورة' },
  'Saisie différée': { ar: 'إدخال مؤجَّل' },
  'Modifier': { ar: 'تعديل' },
  'Modifier la fuite': { ar: 'تعديل التسرب' },
  'Modifier la réfection': { ar: 'تعديل إعادة الرصف', hyb: 'تعديل الـ Réfection' },
  ' : vos ajouts restent possibles (réparation, réfection, photos) ; le reste est réservé au responsable.': { ar: ': يمكنك دائمًا الإضافة (إصلاح، إعادة رصف، صور)؛ والباقي من اختصاص المسؤول.', hyb: ': يمكنك دائمًا الإضافة (إصلاح، Réfection، صور)؛ والباقي من اختصاص المسؤول.' },
  'Déjà validée par le responsable : elle ne se modifie plus depuis la tablette. Ajoutez un nouvel élément (il sera à valider) ou demandez la correction au responsable.': { ar: 'صادق عليها المسؤول: لم يعد تعديلها ممكنًا من الجهاز اللوحي. أضِف عنصرًا جديدًا (سيكون للمصادقة) أو اطلب التصحيح من المسؤول.' },
  'Photo enregistrée avant la validation : seul le responsable peut la modifier ou la retirer.': { ar: 'صورة حُفظت قبل المصادقة: المسؤول وحده يمكنه تعديلها أو إزالتها.' },
  'Validation réservée au responsable.': { ar: 'المصادقة من اختصاص المسؤول.' },
  'Réparation validée : pièces et ouvriers réservés au responsable.': { ar: 'إصلاح مُصادَق عليه: القطع والعمال من اختصاص المسؤول.' },
  'Champs obligatoires manquants : {champs}. Complétez la saisie (Modifier), puis « Envoyer maintenant ».': { ar: 'حقول إلزامية ناقصة: {champs}. أكمِل الإدخال (تعديل)، ثم اضغط «أرسِل الآن».' },
  'Type : {type}': { ar: 'النوع: {type}' },
  'Retirer la photo': { ar: 'إزالة الصورة' },
  'Retirer la photo ?': { ar: 'إزالة الصورة؟' },
  'Elle ne sera plus affichée ; le fichier est gardé et le responsable peut la rétablir.': { ar: 'لن تُعرَض بعد الآن؛ يبقى الملف محفوظًا ويمكن للمسؤول استرجاعها.' },
  'Touchez une photo pour changer son type ou la retirer.': { ar: 'المس صورة لتغيير نوعها أو إزالتها.' },
  'Modification de la fuite · {fuite}': { ar: 'تعديل التسرب · {fuite}' },
  'Modification de réfection · {fuite}': { ar: 'تعديل إعادة الرصف · {fuite}', hyb: 'تعديل الـ Réfection · {fuite}' },
  'Modification de photo · {fuite}': { ar: 'تعديل صورة · {fuite}' },
  'Visibilité': { ar: 'الظهور', hyb: 'Visibilité' },
  'Nature de dégradation': { ar: 'نوع التلف', hyb: 'Nature de dégradation' },
  'Champs obligatoires : {champs}.': { ar: 'حقول إلزامية: {champs}.' },
  '* champ obligatoire': { ar: '* حقل إلزامي' },
  'Une photo de la fuite aide le responsable à la valider. Enregistrer sans photo ?': { ar: 'صورة التسرب تساعد المسؤول على المصادقة عليه. هل تريد الحفظ بدون صورة؟' },
  'Enregistrer sans photo': { ar: 'حفظ بدون صورة' },
  'Suggestions': { ar: 'اقتراحات' },
  "À valider d'un toucher ; rien n'est rempli sans vous.": { ar: 'تُقبَل بلمسة؛ لا شيء يُملأ بدونك.' },
  'Recherche des suggestions…': { ar: 'جارٍ البحث عن اقتراحات…' },
  'Sans réseau : pas de suggestion, saisie manuelle.': { ar: 'دون اتصال: لا اقتراحات، أدخِل يدويًا.' },
  'Position trop imprécise (± {n} m) pour proposer la rue et le secteur.': { ar: 'الموقع غير دقيق بما يكفي (± {n} م) لاقتراح الشارع والقطاع.' },
  'Aucune suggestion ici : saisie manuelle.': { ar: 'لا توجد اقتراحات هنا: أدخِل يدويًا.' },
  'Rue': { ar: 'الشارع' },
  '{rue} (à {n} m)': { ar: '{rue} (على بُعد {n} م)' },
  'Rues : © OpenStreetMap': { ar: 'الشوارع: © OpenStreetMap' },
  'Conduite la plus proche': { ar: 'أقرب قناة' },
  '{conduite} (à {n} m)': { ar: '{conduite} (على بُعد {n} م)' },
  'Liste des natures pas encore chargée sur cette tablette : connectez-la au réseau.': { ar: 'قائمة الأنواع لم تُحمَّل بعد على هذا الجهاز اللوحي: اربطه بالإنترنت.' },
  'Facultatif : matériau et diamètre, si vous les connaissez.': { ar: 'اختياري: المادة والقطر، إن كنت تعرفهما.' },
  'Diamètre (mm)': { ar: 'القطر (مم)' },
  'Diamètre': { ar: 'القطر', hyb: 'Diamètre' },
  'Autre diamètre': { ar: 'قطر آخر' },
  'Facultatives, mais attendues par le responsable ; un appui sur une photo la retire.': { ar: 'اختيارية، لكن المسؤول ينتظرها؛ لمسة على صورة تزيلها.' },
  'Facultatives, mais attendues par le responsable.': { ar: 'اختيارية، لكن المسؤول ينتظرها.' },
  'Ouvrage ou matériau': { ar: 'المنشأة أو المادة' },
  'Comme à la détection : {conduite}': { ar: 'كما عند الكشف: {conduite}' },
  "Choisissez d'abord le matériau : la liste des diamètres en dépend.": { ar: 'اختر المادة أولًا: قائمة الأقطار تتوقف عليها.' },
  'Longueur de conduite posée (m)': { ar: 'طول القناة المُركَّبة (م)' },
  'Longueur de conduite posée': { ar: 'طول القناة المُركَّبة' },
  'En mètres : 0,80 pour 80 cm.': { ar: 'بالأمتار: 0,80 تعني 80 سم.' },
  'Fouille et pièces posées restent à saisir : elles sont attachées même sans réparation.': { ar: 'يجب إدخال الحفرة والقطع المُركَّبة: تُحتسَب حتى بدون إصلاح.' },
  'Un toucher ajoute la pièce ; « − / + » règle la quantité.': { ar: 'لمسة تضيف القطعة؛ «− / +» تضبط الكمية.' },
  'Proposées pour Ø {d} mm': { ar: 'مقترحة لقطر {d} مم' },
  'Proposées pour ce matériau': { ar: 'مقترحة لهذه المادة' },
  'Les plus utilisées': { ar: 'الأكثر استعمالًا' },
  'Rechercher un autre article': { ar: 'البحث عن صنف آخر' },
  'Une de moins : {designation}': { ar: 'واحدة أقل: {designation}' },
  'Une de plus : {designation}': { ar: 'واحدة أكثر: {designation}' },
  'Représentant {sigle} présent (facultatif)': { ar: 'ممثل {sigle} الحاضر (اختياري)' },
  'Aucun représentant dans la liste du marché.': { ar: 'لا يوجد أي ممثل في قائمة الصفقة.' },
  'Saisi auparavant : {nom}': { ar: 'أُدخِل سابقًا: {nom}' },
  'Vérifier et enregistrer': { ar: 'تحقّق واحفظ' },
  'Date et heure': { ar: 'التاريخ والساعة' },
  '{n} m': { ar: '{n} م' },
  'Aucune photo : vous pourrez en ajouter depuis la fiche.': { ar: 'لا توجد صورة: يمكنك إضافتها لاحقًا من البطاقة.' },
  'Dimensions de la fouille ({l} × {la} m)': { ar: 'أبعاد الحفرة ({l} × {la} م)' },
  ' · conduite posée {n} m': { ar: ' · قناة مُركَّبة {n} م' },
  'Récapitulatif de la réparation': { ar: 'ملخص الإصلاح' },
  'Récapitulatif de la réfection': { ar: 'ملخص إعادة الرصف', hyb: 'ملخص الـ Réfection' },
  "Vérifiez avant d'enregistrer. « Corriger » revient au formulaire sans rien perdre.": { ar: 'تحقّق قبل الحفظ. «تصحيح» يعيدك إلى الاستمارة دون أن يضيع شيء.' },
  'Aucune pièce posée.': { ar: 'لم تُركَّب أي قطعة.' },
  'Corriger': { ar: 'تصحيح' },
  'Confirmer': { ar: 'تأكيد' },
  'OK': { ar: 'موافق' },
  'Longueur de la fouille': { ar: 'طول الحفرة' },
  'Largeur de la fouille': { ar: 'عرض الحفرة' },
  'Profondeur de la fouille': { ar: 'عمق الحفرة' },
  '{nom} : {valeur} m, au-delà de {max} m. Les distances sont en mètres (0,80 et non 80) : vérifiez.': { ar: '{nom}: {valeur} م، أكثر من {max} م. المسافات بالأمتار (0,80 وليس 80): تحقّق.' },
  'Conduite posée ({posee} m) plus courte que la plus petite dimension de la fouille ({petite} m) : vérifiez.': { ar: 'القناة المُركَّبة ({posee} م) أقصر من أصغر بُعد للحفرة ({petite} م): تحقّق.' },
  'Conduite posée ({posee} m) plus longue que la plus grande dimension de la fouille ({grande} m) : vérifiez.': { ar: 'القناة المُركَّبة ({posee} م) أطول من أكبر بُعد للحفرة ({grande} م): تحقّق.' },
  'Réfection de {surface} m², au-delà de {max} m². Les distances sont en mètres : vérifiez.': { ar: 'إعادة رصف مساحتها {surface} م²، أكثر من {max} م². المسافات بالأمتار: تحقّق.', hyb: 'Réfection مساحتها {surface} م²، أكثر من {max} م². المسافات بالأمتار: تحقّق.' },
  'Total des réfections de la fuite ({refections} m²) inférieur au total des fouilles ({fouilles} m²).': { ar: 'مجموع إعادة الرصف لهذا التسرب ({refections} م²) أقل من مجموع الحفر ({fouilles} م²).', hyb: 'مجموع الـ Réfection لهذا التسرب ({refections} م²) أقل من مجموع الحفر ({fouilles} م²).' },
  'Notifications': { ar: 'الإشعارات' },
  'Les notifications ont besoin de la connexion.': { ar: 'الإشعارات تحتاج إلى الاتصال بالإنترنت.' },
  'Aucune notification.': { ar: 'لا توجد أي إشعارات.' },
  'Nouvelle fuite N° {numero} détectée': { ar: 'تسرب جديد رقم {numero} تم كشفه' },
  'Réparation saisie : fuite N° {numero}': { ar: 'تم إدخال إصلاح: التسرب رقم {numero}' },
  'Fuite N° {numero} réparée et validée : réfection à faire': { ar: 'التسرب رقم {numero} تم إصلاحه والمصادقة عليه: إعادة الرصف متبقية', hyb: 'التسرب رقم {numero} تم إصلاحه والمصادقة عليه: الـ Réfection متبقية' },
  'Fuite N° {numero} non réparée, fouille validée : réfection à faire': { ar: 'التسرب رقم {numero} لم يُصلَح، الحفرة مُصادَق عليها: إعادة الرصف متبقية', hyb: 'التسرب رقم {numero} لم يُصلَح، الحفرة مُصادَق عليها: الـ Réfection متبقية' },
  'Réfection saisie : fuite N° {numero}': { ar: 'تم إدخال إعادة الرصف: التسرب رقم {numero}', hyb: 'تم إدخال الـ Réfection: التسرب رقم {numero}' },
  'Clôture sans réfection : fuite N° {numero}': { ar: 'إغلاق بدون إعادة رصف: التسرب رقم {numero}', hyb: 'إغلاق بدون Réfection: التسرب رقم {numero}' },
  'Fuite N° {numero} non réparée depuis plus de {delai} h': { ar: 'التسرب رقم {numero} لم يُصلَح منذ أكثر من {delai} ساعة' },
  'Nouvelle version {version} disponible': { ar: 'نسخة جديدة {version} متوفرة' },
  '{taille} Mo à télécharger ; vos saisies et envois en attente sont gardés.': { ar: '{taille} ميغابايت للتحميل؛ إدخالاتك والإرسالات المنتظرة تبقى محفوظة.' },
  'Installer': { ar: 'تثبيت' },
  'Téléchargement… {n} %': { ar: 'جارٍ التحميل… {n} %' },
  'Téléchargement impossible ({erreur}). Réessayez avec une meilleure connexion.': { ar: 'تعذّر التحميل ({erreur}). أعد المحاولة باتصال أفضل.' },
  'fichier incomplet': { ar: 'ملف ناقص' },

  'Voir et ajuster sur la carte': { ar: 'عرض الموقع وضبطه على الخريطة' },
  'Position ajustée sur la carte, à {n} m du GPS.': { ar: 'تم ضبط الموقع على الخريطة، على بُعد {n} م من GPS.' },
  'Position sur la carte': { ar: 'الموقع على الخريطة' },
  "Déplacez l'épingle si besoin, puis « Valider la position ».": { ar: 'حرّك الدبوس عند الحاجة، ثم اضغط «تأكيد الموقع».' },
  'La carte a besoin de la connexion : la position GPS suffit pour enregistrer la fuite.': { ar: 'الخريطة تحتاج إلى الاتصال بالإنترنت: موقع GPS يكفي لتسجيل التسرب.' },
  "La carte ne peut pas s'ouvrir. Réessayez.": { ar: 'تعذّر فتح الخريطة. أعد المحاولة.' },
  'Retour au formulaire': { ar: 'العودة إلى الاستمارة' },

  // Suivi GPS (S11, X6) : libellés à relire par Issam
  'Suivi GPS': { ar: 'تتبع الموقع (GPS)', hyb: 'Suivi GPS' },
  'Suivi de position actif': { ar: 'تتبع الموقع مفعّل' },
  'Le tracé de votre journée est transmis à votre responsable.': { ar: 'يُرسل مسار يومك إلى مسؤولك.' },
  "Le suivi de position n'est pas actif. Touchez ici pour l'activer.": { ar: 'تتبع الموقع غير مفعّل. المس هنا لتفعيله.' },
  'Le suivi de position est actif.': { ar: 'تتبع الموقع مفعّل.' },
  'Le suivi de position est désactivé sur cette tablette.': { ar: 'تتبع الموقع معطّل على هذا الجهاز اللوحي.' },
  "Le suivi de position n'est pas encore actif.": { ar: 'تتبع الموقع غير مفعّل بعد.' },
  "Tant que votre session est ouverte, la tablette enregistre votre parcours (un point tous les 15 m environ) et l'envoie à votre responsable. Une notification reste affichée pendant que le suivi tourne ; elle disparaît avec « Quitter ».": {
    ar: 'ما دامت جلستك مفتوحة، يسجّل الجهاز اللوحي مسارك (نقطة كل 15 م تقريبًا) ويرسله إلى مسؤولك. يبقى إشعار ظاهرًا أثناء عمل التتبع، ويختفي عند الضغط على «خروج».',
  },
  "Seuls votre responsable et l'administrateur voient votre tracé. Il est conservé jusqu'à la fin du marché.": {
    ar: 'لا يرى مسارك إلا مسؤولك ومسؤول النظام. ويُحفظ إلى نهاية الصفقة.',
  },
  "L'autorisation de position est refusée. Ouvrez les réglages de la tablette pour l'accorder.": {
    ar: 'تم رفض إذن الموقع. افتح إعدادات الجهاز اللوحي لمنحه.',
  },
  "Choisissez « Toujours autoriser » pour la position : sans cela, le suivi s'arrête quand l'écran s'éteint.": {
    ar: 'اختر «السماح دائمًا» للموقع: بدون ذلك يتوقف التتبع عند إطفاء الشاشة.',
  },
  'Activer le suivi': { ar: 'تفعيل التتبع' },
  'Ouvrir les réglages de la tablette': { ar: 'فتح إعدادات الجهاز اللوحي' },
  'Désactiver le suivi': { ar: 'إيقاف التتبع' },
  'Batterie (Samsung)': { ar: 'البطارية (سامسونغ)' },
  "Pour que le suivi ne soit pas endormi par la tablette, excluez l'application de l'optimisation de la batterie : Réglages > Batterie > Limites d'utilisation en arrière-plan > Applications jamais en veille > ajoutez « Suivi des fuites ».": {
    ar: 'حتى لا يوقف الجهاز اللوحي التتبع، استثنِ التطبيق من تحسين البطارية: الإعدادات > البطارية > حدود الاستخدام في الخلفية > التطبيقات التي لا تدخل وضع السكون أبدًا > أضف «تتبع التسربات».',
  },
  'Ouvrir les réglages de la batterie': { ar: 'فتح إعدادات البطارية' },
  'État': { ar: 'الحالة' },
  "Points en attente d'envoi : {n}": { ar: 'نقاط في انتظار الإرسال: {n}' },
  'Dernier envoi : {date}': { ar: 'آخر إرسال: {date}' },
  'Aucun envoi pour le moment.': { ar: 'لا يوجد أي إرسال حتى الآن.' },
  'Dernière position enregistrée : {date}': { ar: 'آخر موقع مسجّل: {date}' },
  'Aucune position enregistrée pour le moment.': { ar: 'لا يوجد أي موقع مسجّل حتى الآن.' },

  // Accessibilité (lus par le lecteur d'écran)
  '{legende} : retirer la photo': { ar: '{legende}: إزالة الصورة' },
  'Avancement {progression} %': { ar: 'التقدّم {progression} %' },
} as const satisfies Record<string, Entree>;

export type Cle = keyof typeof TRADUCTIONS;
